version: '3.7'

services:
    app:
        container_name: app
        image: 880403025195.dkr.ecr.us-east-2.amazonaws.com/portfolio-app:1.0.0
        volumes:
            - static_volume:/usr/local/lib/python3.10/site-packages/portfolio/static
        expose:
          - 5678
    nginx:
        container_name: nginx
        image: 880403025195.dkr.ecr.us-east-2.amazonaws.com/portfolio-nginx:1.0.0
        restart: unless-stopped
        volumes:
            - static_volume:/usr/local/lib/python3.10/site-packages/portfolio/static
            # - nginx_secrets:/etc/letsencrypt
        ports:
            - 80:80
            # - 443:443
        depends_on:
            - app

volumes:
    static_volume:
    # nginx_secrets:
