version: '3.7'

services:
    web:
        container_name: portfolio_web
        image: misimpso/portfolio_web:latest
        command: uvicorn main:app --host=0.0.0.0 --port=5000
        volumes:
            - static_volume:/home/portfolio/static
        expose:
            - 5000
    nginx:
        container_name: portfolio_nginx
        image: misimpso/portfolio_nginx:latest
        volumes:
            - static_volume:/home/portfolio/static
        ports:
            - 80:80
        depends_on:
            - web

volumes:
    static_volume:
